print("이름을 입력하세요:", end=" ")
name = input()
print("학번을 입력하세요:", end=" ")
num = input()
print("학과를 입력하세요:", end=" ")
department = input()
print("\n<출력>")
print("이름:",name)
print("학번:",num)
print("학과:",department)
